### ISSUE TITLE
Add z-score as input for wrapper

### ISSUE THREAD

**Issue by pkimes** [pkimes/benchmark-fdr#10]
**Problem:** wrapper script to calc all adjusted p-values currently calculates z-scores by inverting p-values. This is done assuming a 2-sided p-value, which might not be true for all data/simulations considered.

As discussed in PR #9, should use z-scores directly when possible rather than calculating from p-values.

**Comment by kdkorthauer** [comment]
I'm on it! Do you want me to commit the changes directly? Or submit a pull request so it can be reviewed?

**Comment by kdkorthauer** [comment]
((I don't want to break anyone's code by changing the functions, but this change actually shouldn't affect the simulations since it will basically just move where the z-scores are computed to before calling the scott wrapper.))

**Comment by pkimes** [comment]
Ha! Didn't really mean the "Assignment" as literally, but awesome!
PR would be great.
