### ISSUE TITLE
Additional plots and metrics for data applications

### ISSUE THREAD

**Issue by kdkorthauer** [pkimes/benchmark-fdr#13]
For next week (9/29/2017), add the following to the data analyses:

- Diagnostic plot for covariates: are they independent under the null?
- Diagnostic plot for covariates: is it informative under the alternative?
- Comparison of which discoveries are rejected (upsetr)

- [x] GWAS (@kdkorthauer)
- [x] ChIP-seq (@tengmx)
- [x] enrichment analysis (@areyesq89)
- [x] gene-level DE (bulk) (@cshukla)
- [x] gene-level DE (single-cell) (@ayshwaryas)
- [x] microbiome (@cduvallet)
- [x] null simulations (@stephaniehicks)
- [x] non-null simulations (@pkimes)

**Comment by ayshwaryas** [comment]
Fig 1 ("Histograms stratified by the covariate as a diagnostic plot.") in the [IHW paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4930141/) provides an example of the diagnostic plot for covariates. 

"If all histograms look the same, the covariate is uninformative, and its use will not lead to an increase in power. If the tails are no longer uniform, independence under the null is violated, and application of IHW is not valid."

**Comment by cduvallet** [comment]
The IHW [vignette](https://bioconductor.org/packages/release/bioc/vignettes/IHW/inst/doc/introduction_to_ihw.html#diagnostic-plots-for-the-covariate) also recommends making the covariate vs. p-value plots.

> To check whether the covariate is informative about power under the alternative (property 1), plot the p-values (or usually better, −log10⁡(p-values)) against the ranks of the covariate

**Comment by pkimes** [comment]
Finished! and it only took us a year to close the issue!
