### ISSUE TITLE
Why does IHW depend on a nominal alpha value to compute adjusted p-value?

### ISSUE THREAD

**Issue by kdkorthauer** [pkimes/benchmark-fdr#14]
```
library(IHW)

# Code from example in help file of IHW
save.seed <- .Random.seed; set.seed(1)
X   <- runif(20000, min=0, max=2.5)   # covariate
H   <- rbinom(20000,1,0.1)            # hypothesis true or false
Z   <- rnorm(20000, H*X)              # Z-score
pvalue <- 1-pnorm(Z)                  # pvalue

ihw_fdr <- ihw(pvalue, X, .1)  

# try a different alpha value
ihw_fdr2 <- ihw(pvalue, X, .9)  

all.equal(adj_pvalues(ihw_fdr), adj_pvalues(ihw_fdr2))
```
This produces adjusted p-values with "Mean relative difference: 0.144893".

**Comment by areyesq89** [comment]
Could it be because it calculates the weights to optimize the number of rejections for that specific alpha value? For your example:
```
> sum( adj_pvalues(ihw_fdr) < 0.1 )
[1] 238
> sum( adj_pvalues(ihw_fdr2) < 0.1 )
[1] 109
> sum( adj_pvalues(ihw_fdr) < 0.9 )
[1] 4663
> sum( adj_pvalues(ihw_fdr2) < 0.9 )
[1] 7928
```

**Comment by kdkorthauer** [comment]
So it seems that we will need to re-run IHW for each alpha value we compare. This seems like a complication for SummarizedBenchmark. Would it be best to include a separate 'method' for each alpha value? Or create a wrapper that applies IHW separately for each alpha?

**Comment by pkimes** [comment]
@kdkorthauer I think the easiest way to deal with this would be to add a separate 'method' for each alpha value and do some munging of the results before plotting. 
A wrapper might be possible, but I'm not immediately sure how we could take the results from e.g. 10 alphas w/ `ihw` and merge it into a single column in the `SummarizedBenchmark`.

**Comment by pkimes** [comment]
Here's a snippet showing how we could handle multiple `alpha` values for IHW. Note the use of `UQ(ia)` to unquote the `ia`variable so it gets passed to the function as the value (similar to Claire's question about passing variables to `dplyr` as values). 

```
## construct design
bd <- BenchDesign()

## add unadjusted p-values as dummy method
bd %<>% addBMethod("unadjusted", function(x) { x }, x = pval)

## add IHW with different alpha
for (ia in seq(0.01, 0.10, by=0.01)) {
    bd %<>% addBMethod(paste0("ihw_", sprintf("%02g", ia*100)),
                       IHW::ihw,
                       IHW::adj_pvalues,
                       pvalues = pval, covariates = ind_covariate,
                       alpha =  UQ(ia))
}

## simulate toy data (need to source simulation-helpers.R)
sim_df <- du_ttest_sim(m = 20000, pi0 = 0.8, effect_size = 1.5)
names(sim_df)[which(names(sim_df) == "H")] <- "qvalue"

## create SummarizedBenchmark
sb <- buildBench(bd, sim_df, truthCol = "qvalue", ptabular = TRUE)

## calculate eval metrics
sb <- addDefaultMetrics(sb)
tsb <- estimatePerformanceMetrics(sb, alpha=seq(0.01, 0.10, by=0.01), tidy = TRUE)

## plot number of rejections
tsb %>%
    filter(is.na(param.alpha) | (param.alpha == alpha),
           performanceMetric == "rejections") %>%
    ggplot(aes(x = alpha, y = value, color = blabel)) +
    geom_line(alpha=1/3) + geom_point(alpha=1) +
    theme_bw() +
    expand_limits(x=0, y=0) +
    viridis::scale_color_viridis(discrete = TRUE) +
    scale_x_continuous("alpha cutoff", breaks=seq(0, 1, by=0.01)) +
    ylab("Number of Rejections")
```
![example-ihw-alphas](https://user-images.githubusercontent.com/3516025/31308870-9d1d9a34-ab4b-11e7-88ff-bb75d4594eb7.png)

--- 
Here's what it looks like if we don't subset on `param.alpha == alpha`.
```
tsb %>%
    filter(performanceMetric == "rejections",
           grepl("ihw", blabel)) %>%
    ggplot(aes(x = alpha, y = value, color = blabel)) +
    geom_line(alpha=1/3) + geom_point(alpha=1/2) +
    theme_bw() +
    expand_limits(x=0) +
    viridis::scale_color_viridis(discrete = TRUE) +
    scale_x_continuous("alpha cutoff", breaks=seq(0, 1, by=0.01)) +
    ylab("Number of Rejections")
```
![example-ihw-alphas-all](https://user-images.githubusercontent.com/3516025/31308872-a2302a8c-ab4b-11e7-984b-08838d747662.png)

**Comment by pkimes** [comment]
Closing this for now - feel free to re-open. 
I'm using the same approach as in the previous response for the simulations.

See here: 
https://github.com/pkimes/benchmark-fdr/blob/4f03bb/simulation_studies/sim-core.R#L110-L117
