### ISSUE TITLE
JSM sessions

### ISSUE THREAD

**Issue by mikelove** [pkimes/benchmark-fdr#15]
There were two relevant JSM sessions:

This one with Boca and Huber, which you have, but also a method from van de Wiel
https://ww2.amstat.org/meetings/jsm/2017/onlineprogram/ActivityDetails.cfm?SessionID=214148

Also see the first two talks from this session:
https://ww2.amstat.org/meetings/jsm/2017/onlineprogram/ActivityDetails.cfm?SessionID=214047

**Comment by pkimes** [comment]
Can't believe I'm closing this almost a year later. Thanks for the refs! Added AdaPT and decided to leave out SABHA from the sessions.

**Comment by mikelove** [comment]
Did you see this new one

https://www.biorxiv.org/content/early/2018/09/12/414318

**Comment by pkimes** [comment]
yes - unfortunately had to draw a line at some point (that point was last week for us).
