### ISSUE TITLE
FDRreg warning when fitting Z-score distribution

### ISSUE THREAD

**Issue by kdkorthauer** [pkimes/benchmark-fdr#16]
When running the benchmark methods on GWAS data with the `common-BenchDesign.R` script, I get many warnings like so:

```
f(z) misfit = -0.2. Rerun with increased df.
```

I think this is coming from FDRreg. Specifically, when it calls the `efron` function [here](https://github.com/jgscott/FDRreg/blob/master/R_pkg/R/FDRregutils.R). It seems to be an issue with the fitting of the empirical Z-score distribution. The warning suggests to run with an increased degrees of freedom, which is taken from the `control` input list (specifically, the `densknots` parameter). The default value is `densknots`=10, so we could try increasing it, but I'm confused about what the documentation of the FDRreg function says about this parameter:

>  nmids, densknots: Only used if method='efron'; this functionality is retained for legacy reasons and is not recommended for actual data analysis.  nmids: How many histogram midpoints are used in Efron's spline-based estimator of f(z).  Defaults to 150.  densknots: how many spline knots.  Defaults to 10.

From the code it looks like `densknots` is used when method='pr' (default, and what we are using). 

Anyone else run into this warning? Any suggestions on how to handle it?

**Comment by kdkorthauer** [comment]
Additional information: 

- This only occurs for `nulltype="empirical"`
- It no longer occurs for GWAS data analysis when using all SNPs (only get the warning for small subsets)
- @cduvallet has reported seeing the warning, but no one else has had issues

After looking into it, I confirmed that the warning is thrown after estimation of the empirical null density of test statistics. The null density is estimated as done by [Efron (2004)](http://www.stat.cmu.edu/~jiashun/Teaching/F08STAT756/Lectures/Efron.pdf). Essentially, the test statistic is binned into `nmids` bins, and a natural spline with `densknots` df is fit to the bin counts by Poisson regression. 

As mentioned above, the default for `densknots` df is 10, but this parameter can be changed. The `nmids` parameter for number of bins, however, is fixed at 150 (see line 37 [here](https://github.com/jgscott/FDRreg/blob/master/R_pkg/R/FDRreg.R)). Taking a gander at @cduvallet's [p-value histograms](https://github.com/pkimes/benchmark-fdr/blob/master/datasets/microbiome/microbiome-SummarizedBenchmark.html), it is clear that when broken up into 150 bins, there will be lots of zero/very low count bins, with lots of high count bins sprinkled in. I imagine this would be difficult to fit with a smooth curve with 10 df. 

Although the warning message suggests increasing df, I don't believe we actually want to go with an empirical null that is that jagged to fit each of the bumps in the null distribution. It would seem a bit more sensible to either 

1. decrease the number of bins (but this would require modifying code in the FDRreg package), or
2. avoid using the empirical null type for data where the observed distribution of test statistics is not well-behaved. 

I also left an issue here jgscott/FDRreg#2 on the FDRreg repo asking for advice on this manner.

**Comment by pkimes** [comment]
Thanks @kdkorthauer for tracking this all down and filing the issue!

I guess modifying the code at line 37 would be straightforward - we could try it make a pull request.
```
## from
l1 = efron(z, nmids=150, df=mycontrol$densknots, nulltype=nulltype)
## to
l1 = efron(z, nmids=mycontrol$nmids, df=mycontrol$densknots, nulltype=nulltype)
```

**Comment by kdkorthauer** [comment]
Done! Proposed a [pull request](https://github.com/jgscott/FDRreg/pull/3) just modifying two lines that would allow an option to specify nmids.

**Comment by pkimes** [comment]
Awesome! Thanks!!

**Comment by kdkorthauer** [comment]
The pull request for allowing user-specified nmids was accepted. If you re-install FDRreg you'll be able to use the new feature.

@cduvallet if you want to try it out, I've added an 'nmids' argument to the `initializeBenchDesign()` function - it will just modify the call to Scott empirical with a custom nmids. You might have to play around with the actual value of nmids. Below, nmids is set to 100 (default is 150). If this still throws the warning, try an even lower value of nmids (75, 50, etc). 

```
bd <- BenchDesign(nmids=100)
```
