### ISSUE TITLE
Keeping covariates in SummarizeBenchmark objects 

### ISSUE THREAD

**Issue by areyesq89** [pkimes/benchmark-fdr#18]
I wanted to plot, for each method, p-value vs nominal alpha stratified by covariate bins, but realized that currently this information is not in the SummarizedBenchmark object. 

Does it make sense to keep the covariate information in the rowData of the SummarizedBenchmark objects? Is there an option for this in buildBench @pkimes?

**Comment by pkimes** [comment]
Good point. I'll look at adding this.

**Comment by pkimes** [comment]
Shouldn't this be an issue under `SummarizedBenchmark` and not `benchmark-fdr`?

**Comment by areyesq89** [comment]
You are right, sorry!
