### ISSUE TITLE
AdaPT

### ISSUE THREAD

**Issue by stephaniehicks** [pkimes/benchmark-fdr#19]
I added the code for AdaPT (available here: https://github.com/lihualei71/AdaPT/blob/master/AdaPT.R) into the `initializeBenchDesign()` function in datasets/R/common-BenchDesign.R and tried to run it on null simulations. It only ends in an error for me and won't converge. Could someone else try it out and tell me if I'm implementing it wrong?

**Comment by kdkorthauer** [comment]
I am having the same problem. The error message is:
```
!! error caught in buildBench !!
!! error in method: adapt
!!  original message:
!!  Error: cannot find valid starting values: please specify some
```

**Comment by pkimes** [comment]
Closing this since we've decided to leave AdaPT out of the comparison.
