### ISSUE TITLE
Survey simulations and real data analyses 

### ISSUE THREAD

**Issue by pkimes** [pkimes/benchmark-fdr#2]
As a first step to choosing a set of simulation and real data analyses to use for comparing methods, let's take a look at what was used for evaluating each method by their respective authors.

---
To make it easier, let's split this up so one person takes each of the following: 
(**add a comment if you can help!**)

- [x] add notes on IHW simulations [here](../blob/master/notes/2_simulations.md) [@stephaniehicks]
- [x] add notes on ASH simulations [here](../blob/master/notes/2_simulations.md) [@pkimes]
- [x] add notes on Boca-Leek simulations [here](../blob/master/notes/2_simulations.md) [@areyesq89]
- [x] add notes on IHW real data analyses [here](../blob/master/notes/3_realdata.md) [@ayshwaryas]
- [x] add notes on ASH real data analyses [here](../blob/master/notes/3_realdata.md) [@tengmx]
- [x] add notes on Boca-Leek real data analyses [here](../blob/master/notes/3_realdata.md) [@kdkorthauer]

---
Some thoughts on what to include in the summary:
- settings (for simulations) / data type and source (for real data)
- evaluation metrics
- code availability (can we reproduce/modify/extend?)
- other suggestions?

---
Based on 2017/08/28 meeting (notes taken by @kdkorthauer):
> try to include a summary in a couple of sentences: What is the big picture of the simulation scenarios and real data characteristics? Under what global characteristics is each method designed to excel?

**Comment by pkimes** [comment]
Maybe we can agree on a deadline, e.g. 2017/09/01 (next Friday)?

**Comment by stephaniehicks** [comment]
I presented IHW in journal club, so I'm happy to take on IHW. I'll write up a summary for both simulation study and real data analysis. If anyone else wanted to work on IHW too, feel free to join me. 

BTW @pkimes after I click the checkboxes, do I need to click something else to assign that task to myself? Or do I only check the box after the task is complete?

**Comment by pkimes** [comment]
Thanks, @stephaniehicks!

**Comment by pkimes** [comment]
@stephaniehicks hmmm... I don't think GitHub has a way of assigning items in a list. 🤔  

I was thinking we could keep track by adding our names to the items and checking the boxes when we've completed the tasks.

**Comment by kdkorthauer** [comment]
I can take on Boca-Leek since I presented it in Journal Club. Deadline next Friday might be tight for me, but I'll do my best.

**Comment by pkimes** [comment]
Thanks, @kdkorthauer!
If it's tight, don't feel like you need to commit to both simulations and real data (we have 6 people)!
If you want to just take one, we can find someone else to work on the other! 
(and obviously, deadlines are somewhat flexible here 😉)

**Comment by kdkorthauer** [comment]
Got it. Maybe I'll start with real data, and then tackle simulations if no one else has nabbed it yet. Thanks for getting the ball rolling, @pkimes !

**Comment by areyesq89** [comment]
I would be happy to help @kdkorthauer with the simulations of the Boca-Leek paper.

**Comment by tengmx** [comment]
then I will take the ASH real data @pkimes

**Comment by pkimes** [comment]
Thanks, @tengmx, @areyesq89!

**Comment by ayshwaryas** [comment]
Great, thanks Patrick! I'll do the IHW real data summary.

**Comment by pkimes** [comment]
Added notes on ASH simulations - don't really expect anyone to write as much.
Also realized that ASH doesn't have any real data analysis! Lucky @tengmx!

**Comment by tengmx** [comment]
Haha! I should buy powerball @pkimes

**Comment by stephaniehicks** [comment]
I added notes on IHW simulations. Also added a few notes ("idea" or summary of method, "good" or what's good about it, and "bad" what's bad about the method) [here](https://github.com/pkimes/benchmark-fdr/blob/master/notes/1_methods.md).

**Comment by pkimes** [comment]
@stephaniehicks, good idea re:'idea/good/bad'!
don't mind me - just going to add some flair to make it easier to see.

**Comment by pkimes** [comment]
done!
