### ISSUE TITLE
function 'simIteration' and 'addBMethod' missing 

### ISSUE THREAD

**Issue by martinjzhang** [pkimes/benchmark-fdr#21]
Very useful work! 

I tried to run `benchmark-fdr/datasets/simulations/simulations-varyingntests.Rmd` but it can not find the function `simIteration` to generate the data. I searched the entire repo as well as the other repo  `SummarizedBenchmark` but could not find it. Any idea? 

A similar problem occurred when I tried to run `benchmark-fdr/datasets/RNA-Seq/yeast-simulation.Rmd`, where the function `addBMethod` is missing. However, I found another function named `addMethod` in the  `SummarizedBenchmark` repo that seems to be relevant. 

Thanks, 
Martin

**Comment by pkimes** [comment]
Hi Martin, thanks for the interest!

- `simIteration` isn't defined in the SummarizedBenchmark package, it's currently defined in the [`datasets/R/helpers-simulations.R`](https://github.com/pkimes/benchmark-fdr/blob/92ae5ea1b80733fe49c9c622ce52c5d26358b9a6/datasets/R/helpers-simulations.R) file of this repo. Many of the Rmd analyses depend on code in the `datasets/R/` folder, so I recommend downloading these, if not the complete repo, before trying to re-knit. I realize the full repo is big, but a "shallow clone" (just the most recent commit) can be made with the following `git` command. This probably wasn't obvious. I'll add a note to the README.
```bash
 git clone --depth=1 https://github.com/pkimes/benchmark-fdr.git
```
- Backwards incompatible changes where made in the SummarizedBenchmark version >= 1.99.0, and the `addBMethod` was changed in the process. You'll need to use the `fdrbenchmark` branch of the SummarizedBenchmark package. Again, I'll add a note to the README to clarify.
```r
devtools::install_github("areyesq89/SummarizedBenchmark", ref = "fdrbenchmark")
``` 

As a side note, re-knitting the simulation vignettes can take a while, so I recommend running it on a cluster with multiple cores. All simulations were run in parallel on 10 cores. If I remember correctly, depending on the simulation Rmd, this still take a few hours. 

For reference, the HTML output of most Rmds are in [this GitHub repo](https://github.com/pkimes/benchmark-fdr-html), and are [rendered here](http://www.pkimes.com/benchmark-fdr-html/) via GitHub pages.

Let me know if you run into any other issues! 
Feel free to close this issue if the above works for you.

**Comment by martinjzhang** [comment]
Hi Patrick, 

Thanks for the clarification. I did download the entire git repo, but somehow that function was not sourced to the .Rmd file. You may be to check it. 

Anyway, great work, thanks!

**Comment by kdkorthauer** [comment]
Hi Martin,

Which function is still missing? The `simIteration` function is here: https://github.com/pkimes/benchmark-fdr/blob/bff6e877f1c31b86749d6bf9c0ceb184732e88bc/datasets/R/helpers-simulations.R#L59

To access it, you'll need to source the file `datasets/R/helpers-simulations.R`

The `addBMethod` function is in an older version of the `SummarizedBenchmark` package. To get the version we used for the paper, you can do 

```
devtools::install_github("areyesq89/SummarizedBenchmark", ref="fdrbenchmark")
```

Hope that helps!

Best,
Keegan

**Comment by pkimes** [comment]
Hi Martin,

I wonder why the function isn't being sourced for you. That's a little odd. The function should be sourced by the code [here](https://github.com/pkimes/benchmark-fdr/blob/e3f1c887f3324bcc05f4df71f4aa55f8d59e755a/datasets/simulations/simulations-varyingntests.Rmd#L30-L32). The code uses a relative path and `/` to separate directories (i.e. in `../R`), so there might be an issue if the working directory for your R session isn't the `datasets/simulations/` folder or you're working on a system that uses a different path separator.

Let me know if your run into any other problems.
