### ISSUE TITLE
Review/Develop Benchmarking Framework

### ISSUE THREAD

**Issue by pkimes** [pkimes/benchmark-fdr#3]
@areyesq89 made the great 💯  suggestion of creating a R/Bioconductor-based framework for tracking our analysis/results (`SummarizedBenchmark`?).

---
**Existing Frameworks:**
- [iCOBRA (interactive COmparative evaluation of Binary classification and RAnking methods)](https://github.com/markrobinsonuzh/iCOBRA)
- [DSC (Dynamic Statistical Comparisons)](https://github.com/stephens999/dscr)

**Comment by pkimes** [comment]
@areyesq89, let me know if I can help with anything; validators, methods, etc.

**Comment by pkimes** [comment]
It looks like the ASH paper uses something called "DSC"s (developed in the same group) for tracking comparisons:
https://github.com/stephens999/dscr

**Comment by areyesq89** [comment]
DSC looks interesting, I wonder if it also has limitations to keep track of parameters used, etc... With regards to the methods, etc, I was thinking that since anyway we will probably write this for our benchmark, we could implement these methods to receive as input the "SummarizedBenchmark" object?

**Comment by pkimes** [comment]
It looks like DSC **does** track parameters (both simulation and method parameters). 
Just reading through the code and vignette, it looks like the process is:
1. create a `dsc` object (essentially a `new.env()` - kind of like a list?)
2. add pieces of the analysis to the `dsc` object with `add_*` calls
    1. `add_scenario(dsc, ...)`: specify data simulator and parameters
    2. `add_method(dsc, ...)`: specify methods and parameters
    3. `add_score(dsc, ...)`: specify metric to compare methods against 'expected values'
3. run the analysis with `run_dsc`

I like the general idea and structure, but it doesn't seem as appropriate for real data comparisons, and doesn't fit the standard Bioconductor classes. 

--- 
> "we could implement these methods to receive as input the "SummarizedBenchmark" object?"

Do you mean writing a wrapper to (for example) `IHW::ihw(...)` that takes a `SummarizedBenchmark` as input and returns FDR estimates (or a `SummarizedBenchmark` object with a new column)? (I guess we could also just do the wrapper for the `SummarizedExperiment` class if you extend it with the `SummarizedBenchmark` class.) 🤔  ...or am I totally misunderstanding?

**Comment by areyesq89** [comment]
Yes exactly, I was thinking  more in "downstream" functions that are perhaps less specific to our benchmark, like plotROC, plotVennDiagram, etc

**Comment by pkimes** [comment]
Closing since SummarizedBenchmark is already moving along in a separate repo:
https://github.com/areyesq89/SummarizedBenchmark
