### ISSUE TITLE
Identify data sets and simulations

### ISSUE THREAD

**Issue by pkimes** [pkimes/benchmark-fdr#4]
By 2017/09/15, finish follow tasks:

### Real Data:
1. identify >=2 data sets; check data in original papers (**try to actually download**)
2. identify available 'specific' variables (p-values, effect sizes, std. errors)
3. identify 'general' covariates for data set
- [x] GWAS (@kdkorthauer)
- [x] ChIP-seq (@tengmx)
- [x] enrichment analysis (@areyesq89)
- [x] gene-level DE (bulk) (@cshukla)
- [x] gene-level DE (single-cell) (@ayshwaryas)
- [x] microbiome (@cduvallet)

### Simulations:
- [x] discuss simulations (@pkimes, @stephaniehicks)

**Comment by pkimes** [comment]
since @kdkorthauer started organizing things under [`/datasets/GWAS/`](https://github.com/pkimes/benchmark-fdr/tree/master/datasets/GWAS), maybe it would make sense to also organize the other data types under the same folder? 
e.g. `/datasets/ChIP-seq/`, `/datasets/de-bulk/` (or however people feel like naming things).

**Comment by kdkorthauer** [comment]
Feel free to reorganize as you see fit! I just needed a place to stick things for now.
