### ISSUE TITLE
Run methods on identified datasets

### ISSUE THREAD

**Issue by kdkorthauer** [pkimes/benchmark-fdr#6]
By 2017/09/22, finish follow tasks:

### Real Data:
Run the benchmark methods on the datasets that were previously identified. 
- [x] GWAS (@kdkorthauer)
- [x] ChIP-seq (@tengmx)
- [x] enrichment analysis (@areyesq89)
- [x] gene-level DE (bulk) (@cshukla)
- [x] gene-level DE (single-cell) (@ayshwaryas)
- [x] microbiome (@cduvallet)

### Simulations:
- [x] Add additional simulations (@pkimes, @stephaniehicks)

**Comment by ayshwaryas** [comment]
for real datasets:
evaluate "robustness of methods" as defined in [Soneson et al., 2017](http://www.biorxiv.org/content/early/2017/05/28/143289) 

- when applied to different subsets of the same dataset and look for concordance.
- subsets vs the whole dataset to compare FDR-control vs power.
