### ISSUE TITLE
How to run Scott (FDRreg) when some p-values < 2.2e-16?

### ISSUE THREAD

**Issue by kdkorthauer** [pkimes/benchmark-fdr#8]
Scott takes as input Z-scores, but for the real data we don't always have Z-scores. So we could use `qnorm(1-pval/2)*sign(effect_size)` to find the normal quantile for each unadjusted p-value and use that as input to Scott. The problem is that sometimes a p-value might be reported with high precision as a very small negative value, such as less than 2.2e-16. This does happen in the case of GWAS data. In that case the normal quantile from qnorm is reported as infinity (or minus infinity if the effect size is negative). 

What should we do about such cases? Not apply Scott? Impute a Z-score lower than infinity for these p-values?

**Comment by pkimes** [comment]
Imputing sounds dangerous (unless we show that the method is robust to imputed extreme values). I would say drop if we can't run it.
Is it possible to find GWAS data with effect size and SE statistics? 
Looking at a recent GWAS meta-analysis review paper, they claim: 
> ... Nevertheless, summary association statistics are often readily available and can be used to compute z-scores (Fig. 1). Here, we define summary association statistics as per-allele SNP effect sizes (log odds ratios for case–control traits) together with their standard errors, ...

[reference](http://www.nature.com/nrg/journal/v18/n2/full/nrg.2016.142.html)

**Comment by kdkorthauer** [comment]
I agree. When we have effect size & SE it seems safe to compute z-scores, and if not, then we'll skip Scott.
